### ISSUE TITLE
String validation/rust specific string types

### ISSUE THREAD

**Issue by ModProg** [dnaka91/cargo-hatch#1]
1. valid_ident
2. crate-name
3. sem.ver (I don't have any use for that one, just came to mind)
4. a verifying pattern (regex?)

Maybe I will look into implementing this myself

**Comment by dnaka91** [comment]
Just for confirmation, do you mean to add an optional restriction to the strings?
So that when the user is asked to input a value, it'll refuse anything that doesn't match the custom format/pattern?

**Comment by dnaka91** [comment]
Just added support for various string input validators and pushed a new release. 
They're documented over [here](https://github.com/dnaka91/cargo-hatch/blob/main/USAGE.md#string-validators).

**Comment by ModProg** [comment]
Very nice, only nitpick: `Name a crate` as description for everything in the documentation :D

**Comment by dnaka91** [comment]
Ah, he he... Darn copy & paste.
Will improve that tomorrow 😅
